# azure-pipelines meta tag
# Build pipeline for Azure DevOps to build Next.js app and generate artifacts

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build Next.js app'

  - script: |
      npm run export
    displayName: 'Export static site (if using static export)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'out'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy build output to staging directory'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nextjs-app'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'